package com.project.alarm.type;


public enum AlarmType {
    NEW_QUESTION,
    NEW_ANSWER,
    NEW_REPLY,
    NEW_BOARD_ANSWER,
    NEW_RESERVATION_BROKER,
    RESERVATION_APPROVE,
    RESERVATION_CANCEL,
    NEW_BROKER_ACCEPT,
    NEW_BROKER_REJECT
}
